language: android
dist: trusty
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    # - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-28
  licenses:
    - build-tools;28.0.3 Android SDK Build-Tools 28.0.3
